### ISSUE TITLE
Image pointers

### ISSUE THREAD

**Issue by ghost** [WoltLab/WCF#482]
``` css
a,
img[src*='delete'],
img[src*='uninstall'],
img[src*='install'],
img[src*='update'],
img[src*='run'],
img[src*='info'],
img[src*='disable'],
img[src*='enable'] {
    cursor: pointer;
}
```

That declaration is problematic if the path of your installation includes `delete` or one of the others since all images cause the cursor to be a pointer while hovering over them.
